def _mock_patch(feature):
    """A minimal but syntactically valid unified diff: creates a new file,
    so it never depends on matching existing repo content and always
    applies cleanly with `git apply`."""
    path = f"notes/{feature}-mock.md"
    lines = [
        f"# Mock work output for {feature}",
        "",
        "This is a placeholder artifact generated by the mock adapter.",
    ]
    hunk = "\n".join(f"+{line}" for line in lines)
    return (
        f"diff --git a/{path} b/{path}\n"
        "new file mode 100644\n"
        "index 0000000..e69de29\n"
        "--- /dev/null\n"
        f"+++ b/{path}\n"
        f"@@ -0,0 +1,{len(lines)} @@\n"
        f"{hunk}\n"
    )


def send_prompt(prompt_text, context):
    meta = context.get("meta", {})
    phase = meta.get("phase")
    feature = meta.get("feature") or "example"

    if phase == "work":
        response_text = _mock_patch(feature)
    else:
        response_text = (
            "MOCK_RESPONSE\n\n"
            "# Example output\n"
            "- domains:\n"
            "  - Example\n"
            "- bounded_contexts:\n"
            "  - ExampleContext\n"
        )

    return {
        "response_text": response_text,
        "prompt_hash": meta.get("prompt_hash"),
        "rag_sources": meta.get("rag_sources", []),
        "model": "mock",
    }
